
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joetechapp
  namespace: dev
spec:
  selector:
    matchLabels:
      app: joetechapp
  template:
    metadata:
      labels:
        app: joetechapp
    spec:
      containers:
      - name: joetechapp
        image: jeaggrey/webapp:30
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
