apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dev
  name: joetechapp
  labels:
    name: joetechapp
spec:
  ingressClassName: nginx
  rules:
  - host: joe.joetechservices.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: joetechapp
            port:
              number: 80
