apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: "2023-04-09T22:11:17Z"
  generation: 1
  name: joetechapp
  namespace: dev
  resourceVersion: "15122"
  uid: 09cc2b31-b3ae-47d7-b7b5-5eb4ca604eab
spec:
  ingressClassName: nginx
  rules:
  - host: www.joetechservices.com
    http:
      paths:
      - backend:
          service:
            name: joetechapp
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: 104-200-27-207.ip.linodeusercontent.com
      ip: 104.200.27.207
